'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import { Court, Sport } from '@playarena/types';
import { OwnerGuard } from './owner-guard';
import { OwnerNavigation } from './owner-navigation';
import { useAuth } from './use-auth';
import { apiRequest } from '../lib/api';

type EditorMode = 'create' | 'edit';

export function CourtsList() {
  const { session, ownedArenas } = useAuth(); const token = session?.access_token; const arena = ownedArenas[0]; const arenaId = arena?.id; const params = useSearchParams();
  const [courts, setCourts] = useState<Court[] | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!token || !arenaId) return; const accessToken = token; let active = true; void apiRequest<Court[]>(`/owner/arenas/${arenaId}/courts`, accessToken, { cache: 'no-store' }).then((data) => { if (active) setCourts(data); }).catch(() => { if (active) { setError('Não foi possível carregar os campos.'); setCourts([]); } }); return () => { active = false; }; }, [arenaId, token]);
  return <OwnerGuard><main className="courts-page min-h-[100dvh] bg-[#080D14] pb-28 text-white"><div aria-hidden="true" className="courts-ambient fixed inset-x-0 top-0 h-[250px]" /><div className="relative mx-auto w-full max-w-[640px] px-4 pb-6 pt-[max(1.25rem,env(safe-area-inset-top))] sm:px-5"><header className="courts-enter flex items-center justify-between gap-4"><div><h1 className="text-[28px] font-extrabold tracking-[-.055em]">Campos</h1>{courts ? <p className="mt-2 text-xs font-bold uppercase tracking-[.14em] text-[#9DA7B3]">{courts.length} {courts.length === 1 ? 'cadastrado' : 'cadastrados'}</p> : null}</div><Link className="courts-add-button" href="/dashboard/quadras/novo"><span aria-hidden="true">+</span> Adicionar</Link></header>{params.get('created') ? <p className="courts-notice mt-5">Campo criado</p> : null}{error ? <p className="courts-error mt-5">{error}</p> : null}{courts === null ? <CourtsSkeleton /> : courts.length === 0 ? <CourtsEmptyState /> : <section className="mt-7 space-y-2.5">{courts.map((court, index) => <CourtListItem court={court} index={index} key={court.id} />)}</section>}</div><OwnerNavigation /></main></OwnerGuard>;
}

export function CourtEditor({ mode, courtId }: { mode: EditorMode; courtId?: string }) {
  const { session, ownedArenas } = useAuth(); const token = session?.access_token; const arena = ownedArenas[0]; const arenaId = arena?.id; const router = useRouter();
  const [sports, setSports] = useState<Sport[]>([]); const [court, setCourt] = useState<Court | null>(null); const [name, setName] = useState(''); const [duration, setDuration] = useState(60); const [selected, setSelected] = useState<number[]>([]); const [active, setActive] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const lock = useRef(false);
  useEffect(() => { if (!token || !arenaId) return; const accessToken = token; let mounted = true; void (async () => { try { const [sportsData, courts] = await Promise.all([apiRequest<Sport[]>('/sports', accessToken, { cache: 'no-store' }), apiRequest<Court[]>(`/owner/arenas/${arenaId}/courts`, accessToken, { cache: 'no-store' })]); if (!mounted) return; setSports(sportsData); if (mode === 'edit') { const current = courts.find((item) => item.id === courtId) ?? null; if (!current) { setError('Campo não encontrado.'); return; } setCourt(current); setName(current.name); setDuration(current.default_duration_minutes); setSelected(current.sports.map((sport) => sport.id)); setActive(current.active); } } catch { if (mounted) setError('Não foi possível carregar os dados do campo.'); } finally { if (mounted) setLoading(false); } })(); return () => { mounted = false; }; }, [arenaId, courtId, mode, token]);
  function toggleSport(id: number) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !arena || saving || lock.current) return; if (active && selected.length === 0) { setError('Selecione ao menos uma modalidade para um campo ativo.'); return; } lock.current = true; setSaving(true); setError(''); try { if (mode === 'create') { await apiRequest(`/owner/arenas/${arena.id}/courts`, token, { method: 'POST', body: JSON.stringify({ name: name.trim(), default_duration_minutes: duration, active, sport_ids: selected }) }); router.push('/dashboard/quadras?created=1'); } else if (court) { await apiRequest(`/owner/courts/${court.id}`, token, { method: 'PATCH', body: JSON.stringify({ name: name.trim(), default_duration_minutes: duration, active }) }); await apiRequest(`/owner/courts/${court.id}/sports`, token, { method: 'PUT', body: JSON.stringify({ sport_ids: selected }) }); router.push('/dashboard/quadras'); } } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Não foi possível salvar o campo.'); } finally { lock.current = false; setSaving(false); } }
  const title = mode === 'create' ? 'Novo campo' : court?.name ?? 'Campo';
  return <OwnerGuard><main className="courts-page min-h-[100dvh] bg-[#080D14] pb-28 text-white"><div aria-hidden="true" className="courts-ambient fixed inset-x-0 top-0 h-[250px]" /><div className="relative mx-auto w-full max-w-[640px] px-4 pb-6 pt-[max(1.25rem,env(safe-area-inset-top))] sm:px-5"><Link className="courts-back" href="/dashboard/quadras"><ArrowIcon /> Voltar</Link><h1 className="courts-editor-title courts-enter mt-6 text-[28px] font-extrabold tracking-[-.055em]">{title}</h1>{loading ? <EditorSkeleton /> : error && mode === 'edit' && !court ? <p className="courts-error mt-6">{error}</p> : <form className="courts-editor-form courts-enter mt-7" noValidate onSubmit={(event) => void submit(event)}><label>Nome<input autoFocus onChange={(event) => setName(event.target.value)} placeholder="Campo 2" required value={name} /></label><fieldset><legend>Modalidade</legend>{sports.length === 0 ? <p className="courts-muted">Nenhuma modalidade disponível.</p> : <SportPicker selected={selected} sports={sports} toggle={toggleSport} />}</fieldset><label>Duração<select onChange={(event) => setDuration(Number(event.target.value))} value={duration}>{[30, 45, 60, 90, 120].map((value) => <option key={value} value={value}>{value} min</option>)}</select></label>{mode === 'edit' ? <label className="courts-active-toggle"><span><b>Campo ativo</b><small>Disponível para reservas</small></span><input checked={active} onChange={(event) => setActive(event.target.checked)} type="checkbox" /></label> : null}{error ? <p className="courts-error">{error}</p> : null}<button className="courts-create-button" disabled={saving || !name.trim()} type="submit">{saving ? (mode === 'create' ? 'Criando...' : 'Salvando...') : mode === 'create' ? 'Criar campo' : 'Salvar alterações'}</button></form>}</div><OwnerNavigation /></main></OwnerGuard>;
}

function CourtListItem({ court, index }: { court: Court; index: number }) { const sports = court.sports.map((sport) => sport.name); const sportLabel = sports.length > 1 ? `${sports[0]} +${sports.length - 1}` : sports[0] ?? 'Sem modalidade'; return <Link aria-label={`Editar ${court.name}`} className="court-list-item courts-stagger flex min-h-[92px] items-center gap-4 rounded-[18px] p-4" href={`/dashboard/quadras/${court.id}`} style={{ '--court-index': index } as CSSProperties}><span className="court-field-mark"><FieldIcon /></span><span className="min-w-0 flex-1"><b className="block truncate text-base">{court.name}</b><small className="mt-1 block truncate text-sm text-[#9DA7B3]">{sportLabel} <i>•</i> {court.default_duration_minutes} min</small><span className={`court-status ${court.active ? 'is-active' : 'is-inactive'}`}><i />{court.active ? 'Ativo' : 'Inativo'}</span></span><ChevronIcon /></Link>; }
function SportPicker({ sports, selected, toggle }: { sports: Sport[]; selected: number[]; toggle: (id: number) => void }) { return <div className="court-sport-picker">{sports.map((sport) => <button aria-pressed={selected.includes(sport.id)} className={selected.includes(sport.id) ? 'is-selected' : ''} key={sport.id} onClick={() => toggle(sport.id)} type="button"><SportIcon slug={sport.slug} /><span>{sport.name}</span>{selected.includes(sport.id) ? <i>✓</i> : null}</button>)}</div>; }
function CourtsEmptyState() { return <section className="courts-empty-state mt-10 rounded-[22px] border border-white/10 bg-[#111923]/85 p-7 text-center"><span><FieldIcon /></span><h2 className="mt-4 text-lg font-extrabold">Nenhum campo cadastrado</h2><Link className="courts-add-button mt-6 inline-flex" href="/dashboard/quadras/novo"><b>+</b> Adicionar primeiro campo</Link></section>; }
function CourtsSkeleton() { return <div className="mt-7 space-y-2.5"><div className="h-[92px] animate-pulse rounded-[18px] bg-[#111923]" /><div className="h-[92px] animate-pulse rounded-[18px] bg-[#111923]" /></div>; }
function EditorSkeleton() { return <div className="mt-7 space-y-5"><div className="h-16 animate-pulse rounded-[15px] bg-[#111923]" /><div className="h-36 animate-pulse rounded-[18px] bg-[#111923]" /><div className="h-14 animate-pulse rounded-[15px] bg-[#111923]" /></div>; }
function ArrowIcon() { return <svg aria-hidden="true" fill="none" height="18" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" width="18"><path d="m15 18-6-6 6-6M9 12h12" /></svg>; }
function ChevronIcon() { return <svg aria-hidden="true" fill="none" height="20" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" width="20"><path d="m9 18 6-6-6-6" /></svg>; }
function FieldIcon() { return <svg aria-hidden="true" fill="none" height="21" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" viewBox="0 0 24 24" width="21"><rect height="16" rx="2" width="19" x="2.5" y="4" /><path d="M12 4v16M2.5 12h19M8 8h.01M16 16h.01" /></svg>; }
function SportIcon({ slug }: { slug: string }) { const symbol = slug === 'society' ? 'S' : slug === 'beach-tennis' ? 'B' : slug === 'futevolei' ? 'F' : slug === 'tenis' ? 'T' : slug === 'volei' ? 'V' : '+'; return <span aria-hidden="true" className="court-sport-icon">{symbol}</span>; }
