'use client';

import { FormEvent, startTransition, useEffect, useRef, useState } from 'react';
import { DateField } from '../../../components/date-field';
import { OwnerGuard } from '../../../components/owner-guard';
import { OwnerNavigation } from '../../../components/owner-navigation';
import { TimeField } from '../../../components/time-field';
import { useAuth } from '../../../components/use-auth';
import { ApiRequestError, apiRequest, apiRequestWithMeta } from '../../../lib/api';
import { BRAZIL_TIME_ZONE, formatCurrencyBRL, formatTimeBR, parseCurrencyBRL, todayInSaoPaulo } from '../../../lib/format';

type Court = { id: string; name: string };
type Slot = { court_id: string; court_name: string; start_at: string; end_at: string; reservation_id: string | null; customer_name: string | null; price: string | null; status: string | null; source: string | null; blocked_slot_id: string | null; blocked_reason: string | null };
type ReservationAction = { id: string; type: 'confirm' | 'cancel' };
type Mode = 'block' | 'manual' | null;

const visualDate = new Intl.DateTimeFormat('pt-BR', { weekday: 'short', day: '2-digit', month: 'short', timeZone: BRAZIL_TIME_ZONE });

export default function AgendaPage() {
  const { session, ownedArenas } = useAuth(); const token = session?.access_token; const arenaId = ownedArenas[0]?.id;
  const [day, setDay] = useState(todayInSaoPaulo); const [court, setCourt] = useState(''); const [courts, setCourts] = useState<Court[]>([]); const [slots, setSlots] = useState<Slot[] | null>(null); const [isAgendaLoading, setIsAgendaLoading] = useState(true); const [agendaError, setAgendaError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [reservationAction, setReservationAction] = useState<ReservationAction | null>(null); const [mode, setMode] = useState<Mode>(null); const [menuOpen, setMenuOpen] = useState(false); const [start, setStart] = useState('18:00'); const [end, setEnd] = useState('19:00'); const lock = useRef(false);

  async function refresh(accessToken = token) { if (!accessToken) { startTransition(() => setIsAgendaLoading(false)); return; } const params = new URLSearchParams({ day }); if (court) params.set('court_id', court); const path = `/owner/agenda?${params.toString()}`; startTransition(() => { setIsAgendaLoading(true); setAgendaError(''); }); try { const { data } = await apiRequestWithMeta<Slot[]>(path, accessToken); startTransition(() => setSlots(data)); } catch (error) { const status = error instanceof ApiRequestError ? error.status : undefined; if (process.env.NODE_ENV === 'development') console.warn('[OWNER_AGENDA]', { path, status }); startTransition(() => { setSlots([]); setAgendaError('Não foi possível carregar a agenda.'); }); } finally { startTransition(() => setIsAgendaLoading(false)); } }

  useEffect(() => { if (!token || !arenaId) return; const accessToken = token; void apiRequest<Court[]>(`/owner/arenas/${arenaId}/courts`, accessToken).then((data) => startTransition(() => setCourts(data))).catch(() => startTransition(() => setNotice('Não foi possível carregar os campos.'))); }, [arenaId, token]);
  useEffect(() => { void refresh(); }, [day, court, token]); // eslint-disable-line react-hooks/exhaustive-deps

  async function action(path: string, init?: RequestInit, message?: string, pendingAction?: ReservationAction) { if (!token || lock.current) return; lock.current = true; setBusy(true); setReservationAction(pendingAction ?? null); try { await apiRequest(path, token, init); setNotice(message ?? 'Agenda atualizada.'); await refresh(token); if (pendingAction) window.dispatchEvent(new Event('playarena:reservations-changed')); } catch (error) { const errorMessage = error instanceof Error ? error.message : ''; setNotice(errorMessage.includes('acabou de ser reservado') ? 'Esse horário não está mais disponível.' : errorMessage || 'Não foi possível atualizar a agenda.'); } finally { lock.current = false; setBusy(false); setReservationAction(null); } }
  async function submit(event: FormEvent) { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const courtId = String(form.get('court_id')); const startAt = `${day}T${start}:00`; const endAt = `${day}T${end}:00`; if (start >= end) { setNotice('O horário final deve ser posterior ao inicial.'); return; } if (mode === 'block') await action('/owner/blocked-slots', { method: 'POST', body: JSON.stringify({ court_id: courtId, start_at: startAt, end_at: endAt, reason: String(form.get('reason') || 'Bloqueio manual') }) }, 'Horário bloqueado.'); if (mode === 'manual') { const price = parseCurrencyBRL(String(form.get('price'))); if (price === null) { setNotice('Informe um preço válido.'); return; } await action('/owner/reservations/manual', { method: 'POST', body: JSON.stringify({ court_id: courtId, start_at: startAt, end_at: endAt, customer_name: String(form.get('name')), customer_phone: String(form.get('phone')), price }) }, 'Reserva manual criada.'); } setMode(null); }

  const groups = groupSlots(slots ?? []); const pendingCount = new Set((slots ?? []).filter((slot) => slot.status === 'pending' && slot.reservation_id).map((slot) => slot.reservation_id)).size; const isToday = day === todayInSaoPaulo();
  return <OwnerGuard><main className="owner-agenda-page min-h-[100dvh] bg-[#080D14] pb-28 text-white"><div aria-hidden="true" className="owner-agenda-ambient fixed inset-x-0 top-0 h-[260px]" /><div className="relative mx-auto w-full max-w-[640px] px-4 pb-6 pt-[max(1.25rem,env(safe-area-inset-top))] sm:px-5"><header className="agenda-enter flex items-center justify-between gap-4"><div><h1 className="text-[28px] font-extrabold tracking-[-.055em]">Agenda</h1><p className="mt-2 text-sm font-medium text-[#9DA7B3]">{headerDate(day)}</p></div>{pendingCount > 0 ? <span className="agenda-pending-count">{pendingCount} {pendingCount === 1 ? 'pendente' : 'pendentes'}</span> : <CalendarIcon />}</header>
    <section className="agenda-enter mt-6"><div className="agenda-date-navigator"><button aria-label="Dia anterior" onClick={() => setDay(shiftDay(day, -1))} type="button"><ArrowIcon direction="left" /></button><label>{dateNavigatorLabel(day)}<input aria-label="Escolher data" onChange={(event) => setDay(event.target.value)} type="date" value={day} /></label><button aria-label="Próximo dia" onClick={() => setDay(shiftDay(day, 1))} type="button"><ArrowIcon direction="right" /></button></div>{!isToday ? <button className="agenda-today-button" onClick={() => setDay(todayInSaoPaulo())} type="button">Hoje</button> : null}</section>
    <section aria-label="Controles da agenda" className="agenda-toolbar agenda-enter mt-5"><select aria-label="Selecionar campo" onChange={(event) => setCourt(event.target.value)} value={court}><option value="">Todos os campos</option>{courts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="agenda-new-button" onClick={() => setMode('manual')} type="button">+ Novo</button><div className="relative"><button aria-expanded={menuOpen} aria-label="Mais ações" className="agenda-more-button" onClick={() => setMenuOpen(!menuOpen)} type="button"><DotsIcon /></button>{menuOpen ? <div className="agenda-actions-menu"><button onClick={() => { setMenuOpen(false); setMode('block'); }} type="button"><LockIcon /> Bloquear horário</button></div> : null}</div></section>
    {notice ? <p aria-live="polite" className="agenda-notice mt-4">{notice}</p> : null}
    {agendaError ? <section className="agenda-error mt-6"><p>Não foi possível carregar a agenda.</p><button onClick={() => void refresh()} type="button">Tentar novamente</button></section> : isAgendaLoading ? <TimelineSkeleton /> : groups.length === 0 ? <section className="agenda-empty mt-8"><CalendarIcon /><h2>Agenda indisponível neste dia</h2></section> : <section className="agenda-timeline mt-6" key={`${day}-${court}`}>{groups.map(([time, items]) => <TimelineRow action={action} busy={busy} items={items} key={time} reservationAction={reservationAction} time={time} />)}</section>}
  </div><OwnerNavigation />{mode ? <AgendaForm busy={busy} courts={courts} day={day} end={end} mode={mode} onClose={() => setMode(null)} onDay={setDay} onEnd={setEnd} onStart={setStart} onSubmit={submit} start={start} /> : null}</main></OwnerGuard>;
}

function TimelineRow({ time, items, busy, action, reservationAction }: { time: string; items: Slot[]; busy: boolean; action: (path: string, init?: RequestInit, message?: string, pendingAction?: ReservationAction) => Promise<void>; reservationAction: ReservationAction | null }) { return <article className="agenda-time-row"><time>{time}</time><div className="agenda-time-content">{items.map((slot) => <SlotState action={action} busy={busy} key={slot.court_id} reservationAction={reservationAction} slot={slot} />)}</div></article>; }
function SlotState({ slot, busy, action, reservationAction }: { slot: Slot; busy: boolean; action: (path: string, init?: RequestInit, message?: string, pendingAction?: ReservationAction) => Promise<void>; reservationAction: ReservationAction | null }) {
  if (slot.blocked_slot_id) return <div className="agenda-slot-blocked"><span><LockIcon /> {slot.court_name} · Bloqueado</span><button disabled={busy} onClick={() => void action(`/owner/blocked-slots/${slot.blocked_slot_id}`, { method: 'DELETE' }, 'Bloqueio removido.')} type="button">Remover</button></div>;
  if (!slot.reservation_id) return <div className="agenda-slot-free"><span>{slot.court_name}</span><b>Livre</b></div>;
  const pending = slot.status === 'pending'; const active = reservationAction?.id === slot.reservation_id;
  return <div className={`agenda-slot-reservation ${pending ? 'is-pending' : ''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b className="block truncate">{slot.customer_name}</b><p className="mt-1 truncate">{slot.court_name}</p></div>{slot.price ? <strong>{formatCurrencyBRL(slot.price)}</strong> : null}</div><div className="mt-3 flex items-center justify-between gap-3"><StatusBadge status={slot.status ?? ''} />{slot.source === 'arena_manual' ? <span className="agenda-source">Manual</span> : null}</div>{pending ? <div className="mt-3 grid grid-cols-2 gap-2"><button className="agenda-confirm" disabled={busy} onClick={() => void action(`/owner/reservations/${slot.reservation_id}/confirm`, { method: 'POST' }, 'Reserva confirmada.', { id: slot.reservation_id!, type: 'confirm' })} type="button">{active && reservationAction?.type === 'confirm' ? 'Confirmando...' : 'Confirmar'}</button><button className="agenda-reject" disabled={busy} onClick={() => void action(`/owner/reservations/${slot.reservation_id}/cancel`, { method: 'POST' }, 'Reserva recusada.', { id: slot.reservation_id!, type: 'cancel' })} type="button">{active && reservationAction?.type === 'cancel' ? 'Recusando...' : 'Recusar'}</button></div> : null}</div>;
}
function StatusBadge({ status }: { status: string }) { const labels: Record<string, string> = { pending: 'Aguardando', confirmed: 'Confirmada', cancelled: 'Cancelada', completed: 'Concluída', no_show: 'Não compareceu' }; return <span className={`agenda-status is-${status}`}><i>{status === 'confirmed' ? '✓' : null}</i>{labels[status] ?? status}</span>; }
function AgendaForm({ mode, courts, day, start, end, busy, onClose, onDay, onStart, onEnd, onSubmit }: { mode: Exclude<Mode, null>; courts: Court[]; day: string; start: string; end: string; busy: boolean; onClose: () => void; onDay: (value: string) => void; onStart: (value: string) => void; onEnd: (value: string) => void; onSubmit: (event: FormEvent) => Promise<void> }) { return <div className="fixed inset-0 z-40 flex items-end bg-black/65 p-3 backdrop-blur-sm sm:items-center sm:justify-center"><button aria-label="Fechar" className="absolute inset-0" onClick={onClose} type="button" /><form className="agenda-sheet relative w-full max-w-md" noValidate onSubmit={(event) => void onSubmit(event)}><h2>{mode === 'block' ? 'Bloquear horário' : 'Nova reserva manual'}</h2><label>Campo<select name="court_id">{courts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Data<DateField key={`${mode}-${day}`} onChange={onDay} value={day} /></label><div className="grid grid-cols-2 gap-3"><label>Início<TimeField onChange={onStart} quick value={start} /></label><label>Fim<TimeField onChange={onEnd} value={end} /></label></div>{mode === 'block' ? <label>Motivo<input name="reason" placeholder="Manutenção" /></label> : <><label>Cliente<input name="name" required /></label><label>Telefone<input name="phone" required /></label><label>Preço (R$)<input inputMode="decimal" name="price" placeholder="150,00" required /></label></>}<button className="agenda-sheet-submit" disabled={busy} type="submit">{busy ? 'Salvando...' : mode === 'block' ? 'Bloquear horário' : 'Salvar reserva'}</button><button className="agenda-sheet-close" onClick={onClose} type="button">Voltar</button></form></div>; }
function TimelineSkeleton() { return <div className="agenda-timeline mt-7">{['17:00', '18:00', '19:00', '20:00', '21:00'].map((time) => <div className="agenda-time-row" key={time}><time>{time}</time><div className="h-9 animate-pulse rounded bg-white/[.05]" /></div>)}</div>; }
function groupSlots(slots: Slot[]) { const groups = new Map<string, Slot[]>(); slots.forEach((slot) => { const time = formatTimeBR(slot.start_at); groups.set(time, [...(groups.get(time) ?? []), slot]); }); return [...groups.entries()]; }
function shiftDay(day: string, amount: number) { const value = new Date(`${day}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + amount); return value.toISOString().slice(0, 10); }
function dateNavigatorLabel(day: string) { const today = todayInSaoPaulo(); if (day === today) return `Hoje · ${shortDate(day)}`; if (day === shiftDay(today, 1)) return `Amanhã · ${shortDate(day)}`; return shortDate(day); }
function headerDate(day: string) { return visualDate.format(new Date(`${day}T12:00:00Z`)).replace('.', '').replace(/^./, (letter) => letter.toUpperCase()); }
function shortDate(day: string) { return new Intl.DateTimeFormat('pt-BR', { weekday: 'short', day: '2-digit', month: 'short', timeZone: BRAZIL_TIME_ZONE }).format(new Date(`${day}T12:00:00Z`)).replace('.', '').toUpperCase(); }
function ArrowIcon({ direction }: { direction: 'left' | 'right' }) { return <svg aria-hidden="true" fill="none" height="20" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" width="20"><path d={direction === 'left' ? 'm15 18-6-6 6-6' : 'm9 18 6-6-6-6'} /></svg>; }
function CalendarIcon() { return <svg aria-hidden="true" className="agenda-calendar-icon" fill="none" height="22" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width="22"><rect height="16" rx="3" width="18" x="3" y="5" /><path d="M8 3v4M16 3v4M3 10h18" /></svg>; }
function DotsIcon() { return <svg aria-hidden="true" fill="currentColor" height="18" viewBox="0 0 24 24" width="18"><circle cx="5" cy="12" r="1.7" /><circle cx="12" cy="12" r="1.7" /><circle cx="19" cy="12" r="1.7" /></svg>; }
function LockIcon() { return <svg aria-hidden="true" fill="none" height="16" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24" width="16"><rect height="11" rx="2" width="14" x="5" y="10" /><path d="M8 10V7a4 4 0 0 1 8 0v3" /></svg>; }
